package Entidades;
// Generated 13-may-2019 12:34:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa  implements java.io.Serializable {


     private int idDetalleVenta;
     private Material material;
     private Venta venta;
     private int cantidad;
     private BigDecimal subtotal;

    public Detalleventa() {
    }

    public Detalleventa(int idDetalleVenta, Material material, Venta venta, int cantidad, BigDecimal subtotal) {
       this.idDetalleVenta = idDetalleVenta;
       this.material = material;
       this.venta = venta;
       this.cantidad = cantidad;
       this.subtotal = subtotal;
    }
   
    public int getIdDetalleVenta() {
        return this.idDetalleVenta;
    }
    
    public void setIdDetalleVenta(int idDetalleVenta) {
        this.idDetalleVenta = idDetalleVenta;
    }
    public Material getMaterial() {
        return this.material;
    }
    
    public void setMaterial(Material material) {
        this.material = material;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }




}


