package Entidades;
// Generated 13-may-2019 12:34:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material  implements java.io.Serializable {


     private int idMaterial;
     private Categoria categoria;
     private String nombre;
     private BigDecimal precio;
     private int stock;
     private Set detalleventas = new HashSet(0);

    public Material() {
    }

	
    public Material(int idMaterial, Categoria categoria, String nombre, BigDecimal precio, int stock) {
        this.idMaterial = idMaterial;
        this.categoria = categoria;
        this.nombre = nombre;
        this.precio = precio;
        this.stock = stock;
    }
    public Material(int idMaterial, Categoria categoria, String nombre, BigDecimal precio, int stock, Set detalleventas) {
       this.idMaterial = idMaterial;
       this.categoria = categoria;
       this.nombre = nombre;
       this.precio = precio;
       this.stock = stock;
       this.detalleventas = detalleventas;
    }
   
    public int getIdMaterial() {
        return this.idMaterial;
    }
    
    public void setIdMaterial(int idMaterial) {
        this.idMaterial = idMaterial;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }




}


